<?php
/**
 * Marker positions on assets/img/map-americas.svg, as percentages of the image box.
 * Generated by theme-src/map.mjs from lat/long (Mercator). Regenerate there if the map changes.
 * Every location opens a card on hover or tap. Canada bases use the small dot marker; the three head offices use the pin.
 * Photos are client photos from the dev-site library, each used once on the About page.
 */
return [
	'dots'    => [],
	'markers' => [
		'midland'        => [ 'px' => 50.68, 'py' => 55.94, 'open' => true, 'pin' => true, 'country' => 'United States', 'city' => 'Midland, TX', 'phone' => '+1.713.300.5216', 'email' => 'PTE.Sales@ptenergy.com', 'photo' => 'map-midland-v2' ],
		'calgary'        => [ 'px' => 43.76, 'py' => 44.70, 'open' => false, 'country' => 'Canada', 'city' => 'Calgary, AB', 'phone' => '+1.780.933.0404', 'email' => 'PTCT.Sales@ptenergy.com', 'photo' => 'map-calgary' ],
		'colombia'       => [ 'px' => 66.75, 'py' => 68.63, 'open' => false, 'country' => 'South America', 'city' => 'Colombia', 'phone' => '+57.321.320.2213', 'email' => 'PTESAS.Sales@ptenergy.com', 'photo' => 'map-colombia-v2' ],
		'grande-prairie' => [ 'px' => 41.04, 'py' => 41.71, 'open' => false, 'country' => 'Canada', 'city' => 'Grande Prairie, AB', 'phone' => '+1.780.288.6128', 'email' => 'PTCT.Sales@ptenergy.com', 'photo' => 'map-grande-prairie' ],
		'red-deer'       => [ 'px' => 43.91, 'py' => 43.85, 'open' => false, 'country' => 'Canada', 'city' => 'Red Deer, AB', 'phone' => '+1.780.933.0404', 'email' => 'PTCT.Sales@ptenergy.com', 'photo' => 'map-red-deer' ],
	],
];
