<?php
/**
 * Marker positions on assets/img/map-americas.svg, as percentages of the image box.
 * Generated by theme-src/map.mjs from lat/long (Mercator). Regenerate there if the map changes.
 */
return [
	'dots' => [
		[ 'px' => 41.04, 'py' => 41.71 ], // Grande Prairie
		[ 'px' => 43.91, 'py' => 43.85 ], // Red Deer
	],
	'markers' => [
		'midland' => [ 'px' => 50.68, 'py' => 55.94, 'open' => true, 'pin' => true, 'country' => 'United States', 'city' => 'Midland, TX', 'phone' => '+1.713.300.5216', 'email' => 'PTE.Sales@ptenergy.com', 'photo' => 'map-midland' ],
		'calgary' => [ 'px' => 43.76, 'py' => 44.70, 'open' => false, 'country' => 'Canada', 'city' => 'Calgary, AB', 'phone' => '+1.780.933.0404', 'email' => 'PTCT.Sales@ptenergy.com', 'photo' => 'map-calgary' ],
		'colombia' => [ 'px' => 66.75, 'py' => 68.63, 'open' => false, 'country' => 'South America', 'city' => 'Colombia', 'phone' => '+57.321.320.2213', 'email' => 'PTESAS.Sales@ptenergy.com', 'photo' => 'map-colombia' ],
	],
];
